### ISSUE TITLE
Add higher priority tasks feature

### ISSUE THREAD

**Issue by JanWielgus** [JanWielgus/Tasker#3]
If the list of tasks grows bigger and bigger high frequency tasks execution precision decrease because they are checked less times per second. If the whole list of important tasks will be checked before checking the next less important task this should increase precision of the whole system.

Maybe two options (priotity: HIGH, LOW) will be sufficient but think about three options.

**Comment by JanWielgus** [comment]
This should work like old bike computers. The fastest ring turns the next ring every full rotation. The next ring is rotated every full rotation of the previous ring etc.. This should do the job.

**Comment by JanWielgus** [comment]
**I have another idea for this.**

Create enum with time precisions, for example 1us, 100us, 1ms, 100ms ...
For each precision there will be separate array of tasks. Only tasks with 1us precision will be checked as fast as possible but all other only, every its precision time (array of tasks with 1ms precision time will be checked every 1ms)
This will create something like priority but more precisely defined.

**Comment by JanWielgus** [comment]
The last idea have to be well-thought-out. Problem in implementation is in storing tasks of lower priority. ObjectTasker was designed to store one array of tasks and its size have to be known when creating the Tasker. The reason of that was to make Tasker simple and fast. Using my GrowingArray library will partially solve the problem, but it will cost memory (but maybe that way) (problem will maxAmountOfTasks in the constructor)

**Comment by JanWielgus** [comment]
There is a way that get around almost all problems: creating two Taskers and put one inside the second one as a task (example code of that is in the repository named ObjTaskerPrioritiesImitation_example)

**Comment by Aleksy-niamik** [comment]
Resolved by checking only the earliest task. All the tasks are checked when task is executed.
